(function(g){var window=this;'use strict';var G4=function(a){a.oa("cardstatechange",a.vk()&&a.Ho()?1:0)},H4=function(a,b){var c=g.Sa(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},Idb=function(a){var b=g.An(a);
a=g.Un(a);return new g.pn(b.x,b.y,a.width,a.height)},K4=function(a){a=g.Wa(a);
delete I4[a];g.fd(I4)&&J4&&J4.stop()},Kdb=function(){J4||(J4=new g.pq(function(){Jdb()},20));
var a=J4;a.isActive()||a.start()},Jdb=function(){var a=g.Za();
g.Uc(I4,function(b){Ldb(b,a)});
g.fd(I4)||Kdb()},L4=function(a,b,c,d){g.Jq.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.K=b;this.duration=c;this.D=d;this.coords=[];this.progress=this.J=0;this.C=null},Ldb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.J=1E3/(b-a.C);a.C=b;Mdb(a,a.progress);1==a.progress?(a.j=0,K4(a),a.onFinish(),a.Nq()):a.md()&&a.uJ()},Mdb=function(a,b){"function"===typeof a.D&&(b=a.D(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.K[c]-a.u[c])*b+a.u[c]},Ndb=function(a,b){g.wb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.J;this.state=b.j},M4=function(a,b,c,d,e){L4.call(this,b,c,d,e);
this.element=a},Odb=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
M4.call(this,a,b,c,d,e)},Pdb=function(a){return Math.pow(a,3)},Qdb=function(a){return 3*a*a-2*a*a*a},Rdb=function(a){g.C.call(this);
this.u=a||window;this.j=[]},N4=function(a){return a.baseUrl||null},O4=function(a,b){return g.Eo(g.Im(a,b),function(c){return!!c})},Sdb=function(a,b,c){function d(X){var ma=X.hovercardButton;
if(!ma)return null;ma=ma.subscribeButtonRenderer;if(!ma)return null;var ba=f(ma.unsubscribedButtonText),Ca=f(ma.subscribedButtonText);if(ma.subscribed){var V=f(ma.subscriberCountWithUnsubscribeText);var Ta=f(ma.subscriberCountText)}else V=f(ma.subscriberCountText),Ta=f(ma.subscriberCountWithSubscribeText);var r=null;if(X.signinEndpoint){r=H4(X,"signinEndpoint","webNavigationEndpointData","url");if(!r){var P,nb;r=null==(nb=g.Q(null==(P=ma.signInEndpoint)?void 0:P.commandMetadata,g.z3))?void 0:nb.url}if(!r)return null}return ba&&
(Ca||r)?{subscribed:ma.subscribed,subscribeText:ba,subscribeCount:V,unsubscribeText:Ca,unsubscribeCount:Ta,enabled:ma.enabled,signinUrl:r,classic:X.useClassicSubscribeButton}:null}
function e(X){if(X){var ma=[],ba=X.videoId;ba&&ma.push("v="+ba);(ba=X.playlistId)&&ma.push("list="+ba);(X=X.startTimeSeconds)&&ma.push("t="+X);return"/watch?"+ma.join("&")}}
function f(X){if(!X)return null;var ma=X.simpleText;return ma?ma:X.runs?g.Im(X.runs,function(ba){return ba.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,t=null,v=null,y=null,A=!1,G=null,N=null,L=null,H=null,U=null,Z=null;if("VIDEO"===h)g.Q(l,g.AO)?m=g.Q(l,g.AO).url:(Z=g.Q(l,g.zO),m=e(Z)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,t=f(p.text),p="LIVE"===p.style):t=f(b.videoDuration);else if("PLAYLIST"===h)g.Q(l,g.AO)?m=g.Q(l,g.AO).url:(Z=g.Q(l,g.zO),m=e(Z)),n=!1,q=a,v=f(b.playlistLength);else if("CHANNEL"===
h){if(A=H4(l,"browseEndpoint","browseId"))y=A,m="/channel/"+y;n=!1;q="new";(A=!!b.isSubscribe)?G=d(b):N=f(b.subscribersText)}else"WEBSITE"===h?((L=H4(l,"urlEndpoint","url"))&&(m=L),n=!0,q="new",L=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(U=f(b.additionalFeesText)),(n=H4(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=H4(b,"title","accessibility","accessibilityData","label");var fa=b.endpoint?b.endpoint.clickTrackingParams:null,
ta="";if(b.metadata){var na=f(b.metadata);na&&(ta=na)}return{id:"element-"+c,type:h,title:f(b.title),metadata:ta,callToAction:f(b.callToAction),PT:b.image,iconUrl:L,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:t,uC:p,playlistLength:v,channelId:y,subscribeButton:G,subscribersText:N,isSubscribe:A,Xt:m||null,P4:n,sessionData:fa?{itct:fa}:null,F9:q,XA:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:O4(b.impressionUrls||[],N4),E4:O4(b.hovercardShowUrls||[],N4),clickUrls:O4(l.loggingUrls||[],N4),visualElement:g.BG(b.trackingParams),productPrice:H,additionalFeesText:U,watchEndpoint:Z||null}},Tdb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:O4(a.impressionUrls||[],N4),elements:O4(a.elements||[],function(d,e){return Sdb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.BG(a.trackingParams));return c},Udb=function(a){g.fU.call(this,a);
this.B=this.endscreen=null;this.j={};this.D={};this.C=this.u=null;this.K=[];this.ea=!0;this.J=0;a=a.W();this.V=g.yM(a)||"profilepage"===a.Na;this.events=new g.iK(this);g.E(this,this.events);this.events.T(this.player,g.aG("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.bG("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.Hb);this.events.T(window,"focus",this.n8);this.load();var b=g.bf("STYLE");(g.Pe("HEAD")[0]||document.body).appendChild(b);g.sb(this,
function(){g.nf(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Vdb=function(a){return a.player.getVideoData().Cd?"current":a.V?"new":"current"},P4=function(a){return"creator-endscreen-editor"===a.player.W().playerStyle},Wdb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=Tdb(f,Vdb(a))));Q4(a,f)},
urlParams:{v:c},withCredentials:!0};a.V&&(c.urlParams.ptype="embedded");var d=b.Yw;d&&(c.postParams={ad_tracking:d});if(b=g.Oya(b))if(b=g.de(b),b=g.Vd(b))a.B=g.Dz(b,c)},Q4=function(a,b,c){c=void 0===c?!0:c;
a.player.Ne("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.u(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.D={};0<a.K.length&&(a.K.forEach(function(l){l.dispose()}),a.K.length=0);
a.J=0;if((a.endscreen=b)&&b.elements){c&&Xdb(a);c=[];d=new g.ZF(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.W().u||(a.u=new g.W({G:"div",S:"ytp-ce-shadow"}),g.eT(a.player,a.u.element,4),a.C=new g.GR(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=Ydb(a,e);if(f){a.j[e.id]=f;a.D[e.id]=e;g.eT(a.player,f.element,4);var h=new g.ZF(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);Zdb(a,f,e)}else g.FF(new g.$A("buildEndscreenElement null",
e))}a.player.cf(c);a.Hb()}},Xdb=function(a){var b=g.DG(),c=g.EG();
c&&b&&a.endscreen.visualElement&&g.iz(g.sQ)(void 0,c,b,a.endscreen.visualElement)},Ydb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={G:"div",La:["ytp-ce-element","ytp-ce-video"],Y:{tabindex:"0","aria-label":b.XA||"","aria-hidden":"true"},X:[{G:"div",S:"ytp-ce-element-shadow"},{G:"div",S:"ytp-ce-covering-image",Y:R4(b)},{G:"div",S:"ytp-ce-covering-shadow-top"},{G:"a",S:"ytp-ce-covering-overlay",Y:{href:S4(a,b.Xt),tabindex:"-1"},X:[{G:"div",La:["ytp-ce-video-title","ytp-webkit-ellipsis"],Y:{dir:g.Nq(b.title||"")},xa:b.title},{G:"div",S:b.uC?"ytp-ce-live-video-duration":"ytp-ce-video-duration",xa:b.videoDuration||
void 0}]}]};c=new g.W(a);break;case "PLAYLIST":a={G:"div",La:["ytp-ce-element","ytp-ce-playlist"],Y:{tabindex:"0","aria-label":b.XA||"","aria-hidden":"true"},X:[{G:"div",S:"ytp-ce-element-shadow"},{G:"div",S:"ytp-ce-covering-image",Y:R4(b)},{G:"div",S:"ytp-ce-covering-shadow-top"},{G:"a",S:"ytp-ce-covering-overlay",Y:{href:S4(a,b.Xt),tabindex:"-1"},X:[{G:"div",La:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],Y:{dir:g.Nq(b.title||"")},xa:b.title},{G:"div",S:"ytp-ce-playlist-count",X:[{G:"div",S:"ytp-ce-playlist-icon"},
{G:"div",S:"ytp-ce-playlist-count-text",xa:b.playlistLength||void 0}]}]}]};c=new g.W(a);break;case "CHANNEL":c={G:"div",La:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],Y:{tabindex:"0","aria-label":b.XA||"","aria-hidden":"true"},X:[{G:"div",S:"ytp-ce-element-shadow"},{G:"div",S:"ytp-ce-expanding-overlay",X:[{G:"div",S:"ytp-ce-expanding-overlay-hider"},{G:"div",S:"ytp-ce-expanding-overlay-background"},{G:"div",S:"ytp-ce-expanding-overlay-content",X:[{G:"div",
S:"ytp-ce-expanding-overlay-body",X:[{G:"div",S:"ytp-ce-expanding-overlay-body-padding",X:[{G:"a",La:["ytp-ce-channel-title","ytp-ce-link"],Y:{href:S4(a,b.Xt),target:"_blank",tabindex:"-1",dir:g.Nq(b.title||"")},xa:b.title},b.subscribeButton?{G:"div",S:"ytp-ce-subscribe-container",X:[{G:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{G:"div",S:"ytp-ce-channel-subscribers-text",xa:b.subscribersText}:"",b.metadata?{G:"div",La:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
xa:b.metadata}:""]}]}]}]},{G:"div",S:"ytp-ce-expanding-image",Y:R4(b)}]};c=new g.W(c);var d=g.Qe(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.xq(d,"ytp-ce-subscribe-button");if(a.player.W().u){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.OU(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player);d.appendChild(e.element);a.K.push(e)}break;case "WEBSITE":a={G:"div",La:["ytp-ce-element","ytp-ce-website"],Y:{tabindex:"0","aria-label":b.XA||"","aria-hidden":"true"},X:[{G:"div",S:"ytp-ce-element-shadow"},{G:"div",S:"ytp-ce-expanding-overlay",X:[{G:"div",S:"ytp-ce-expanding-overlay-hider"},{G:"div",S:"ytp-ce-expanding-overlay-background"},{G:"div",S:"ytp-ce-expanding-overlay-content",X:[{G:"div",S:"ytp-ce-expanding-overlay-body",X:[{G:"div",
S:"ytp-ce-expanding-overlay-body-padding",X:[{G:"div",S:"ytp-ce-website-title",Y:{dir:g.Nq(b.title||"")},xa:b.title},{G:"div",S:"ytp-ce-website-metadata",xa:b.metadata},{G:"a",La:["ytp-ce-website-goto","ytp-ce-link"],Y:{href:S4(a,b.Xt),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{G:"div",S:"ytp-ce-expanding-image",Y:R4(b)},{G:"div",S:"ytp-ce-expanding-icon",Y:$db(b.iconUrl)}]};c=new g.W(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={G:"div",S:"ytp-ce-merchandise-price-container",
X:[{G:"div",S:"ytp-ce-merchandise-price",xa:b.productPrice}]},b.additionalFeesText&&c.X.push({G:"div",S:"ytp-ce-merchandise-additional-fees",xa:b.additionalFeesText})),a={G:"div",La:["ytp-ce-element","ytp-ce-merchandise"],Y:{tabindex:"0","aria-label":b.XA||"","aria-hidden":"true"},X:[{G:"div",S:"ytp-ce-element-shadow"},{G:"div",S:"ytp-ce-expanding-overlay",X:[{G:"div",S:"ytp-ce-expanding-overlay-hider"},{G:"div",S:"ytp-ce-expanding-overlay-background"},{G:"div",S:"ytp-ce-expanding-overlay-content",
X:[{G:"div",S:"ytp-ce-expanding-overlay-body",X:[{G:"div",S:"ytp-ce-expanding-overlay-body-padding",X:[{G:"div",S:"ytp-ce-merchandise-title",Y:{dir:g.Nq(b.title||"")},xa:b.title},c,{G:"div",S:"ytp-ce-merchandise-metadata",xa:b.metadata},{G:"a",La:["ytp-ce-merchandise-goto","ytp-ce-link"],Y:{href:S4(a,b.Xt),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{G:"div",S:"ytp-ce-expanding-image",Y:R4(b)},{G:"div",S:"ytp-ce-merchandise-invideo-cta-container",X:[{G:"div",S:"ytp-ce-merchandise-invideo-cta",
xa:b.callToAction||void 0}]}]},c=new g.W(a)}b.isPlaceholder&&g.xq(c.element,"ytp-ce-placeholder");return c},R4=function(a){if(a.PT)var b=a.PT.thumbnails;
return $db(b?b[b.length-1].url:null)},$db=function(a){return a?{style:"background-image: url("+a+")"}:{}},Zdb=function(a,b,c){function d(m){m&&(b.Ta("blur",function(){"none"!=m.style.display&&a.ea&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.J+=m;0<a.J?(g.xq(b.element,"ytp-ce-force-expand"),T4(a,c.id,!0)):(g.zq(b.element,"ytp-ce-force-expand"),g.zq(b.element,"ytp-ce-element-hover"),T4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ta("mouseenter",function(){aeb(a,b,c)});
b.Ta("mouseleave",function(){beb(a,b,c)});
a.player.W().u||b.Ta("click",function(){g.xq(b.element,"ytp-ce-element-hover")});
b.Ta("click",function(m){ceb(a,c,m)});
b.Ta("keypress",function(m){ceb(a,c,m)});
b.Ta("focus",function(){aeb(a,b,c)});
b.Ta("blur",function(){beb(a,b,c)});
b.Ta("touchstart",function(){aeb(a,b,c)});
var l=g.We("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){g.aQ?m.stopPropagation():(m=m||window.event,m.cancelBubble=!0,m.stopPropagation&&m.stopPropagation());g.zq(b.element,"ytp-ce-element-hover");g.zq(b.element,"ytp-ce-force-expand")});
b.Ta("keydown",function(m){a.ea=9===m.keyCode&&!m.shiftKey});
d(g.We("ytp-sb-subscribe",b.element));d(g.We("ytp-sb-unsubscribe",b.element));b.Ta("focus",f);b.Ta("blur",h)},ceb=function(a,b,c){if(b.Xt&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.wq(d,"ytp-ce-element");){g.wq(d,"subscribe-label")&&deb(a,b);
if(g.wq(d,"ytp-ce-channel-subscribe"))return;d=g.of(d)}if(!d||g.wq(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])beb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.F9)deb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.de(S4(a,b.Xt)),g.DP(g.Vd(c),void 0,b.sessionData);else{var e=g.QM(a.player.W())||a.player.getVideoData().Cd,f=function(){var h=S4(a,b.Xt),l=b.sessionData,m=b.watchEndpoint,n=g.oz(h);e&&n&&(n.v||n.list)?a.player.Wn(n.v,
l,n.list,!1,void 0,m||void 0):g.vza(h,l)};
deb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},S4=function(a,b){a=a.player.W();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.ZM(a)+b}else return"";return b},aeb=function(a,b,c){g.wq(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.xq(b.element,"ytp-ce-element-hover"):a.player.W().u?(new g.pq(function(){g.xq(b.element,"ytp-ce-element-hover")},200)).start():g.xq(b.element,"ytp-ce-element-hover"),U4(a,c.E4),T4(a,c.id,!0))},beb=function(a,b,c){g.zq(b.element,"ytp-ce-element-hover");
g.zq(b.element,"ytp-ce-force-expand");T4(a,c.id,!1)},T4=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.u(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.Bq(a.j[e].element,"ytp-ce-element-shadow-show",c)},U4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||P4(a))c&&c();else{b=eeb(a,b);var e=0,f=!1,h=new g.pq(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.TC(b[a],d)}},deb=function(a,b,c){U4(a,b.clickUrls,c);
(a=g.EG())&&b.P4&&g.yQ(a,b.visualElement)},eeb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(feb(b[d],c));return a},feb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},geb=function(a){return"string"===typeof a?a:""},V4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},heb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},W4=function(a){return a.value?a.value:null},X4=function(a){if(!a)return null;
var b=g.de(geb(a.value));b=g.Vd(b);if(!b)return null;var c=V4(a.target,ieb,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new heb(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},jeb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},meb=function(a){if(!a)return null;
var b=V4(a.type,keb),c=V4(a.trigger,leb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=X4(a?a:null);return b?new jeb(b,c,a):null},neb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},oeb=function(a,b){return g.Eb(a.action,b)},peb=function(a,b){this.context=a;
this.j=b},qeb=function(a){return a.customMessage?Y4("div","iv-card-message",a.customMessage):""},Z4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{G:"div",S:"iv-card-image",Y:{style:a},X:c}},reb=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.u(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(Y4("li","",c.value));return{G:"ul",S:"iv-card-meta-info",X:b}},Y4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Nq(c);return{G:a,Y:b,xa:c}},seb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.gB&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.gB+");");c.dir=g.Nq(a.customMessage);var d=[{G:"span",xa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",S:"iv-card-link-icon"}));return{G:"div",La:b,Y:c,X:d}},$4=function(a,b,c,d){if(d){b=g.u(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.Wi.click,5)}},teb=function(a,b){this.merchant=a;
this.price=b},ueb=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},veb=function(a,b){return b?b:ueb(a)?"current":"new"},a5=function(a,b){g.C.call(this);
var c=this;this.element=a;this.context=b;this.ub=!1;this.bb=new Map;this.jb=new Map;this.context.I.addEventListener(g.aG("annotations_module"),function(d){(d=c.bb.get(d))&&d.apply(c)});
this.context.I.addEventListener(g.bG("annotations_module"),function(d){(d=c.jb.get(d))&&d.apply(c)})},b5=function(a,b,c,d,e,f,h){a.context.j.Ta(b,"click",function(l){a.vJ(c,d,e,f||[],h||0,l)});
a.context.j.Ta(b,"touchstart",function(){a.ub=!1});
a.context.j.Ta(b,"touchmove",function(){a.ub=!0})},web=function(a){var b;
return(null==(b=g.Q(a,g.AO))?0:b.url)?g.Q(a,g.AO).url:(a=g.Q(a,g.zO))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},c5=function(a,b,c){return{kV:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
IY:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
FI:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},xeb=function(a,b,c){a5.call(this,b,c);
var d=this;this.I=a;this.eventId=null;this.Na=this.Rb=this.B=this.isInitialized=!1;this.cards=[];this.Pb=this.V=this.Ja=this.D=this.Va=this.j=null;this.ma=[];this.qa=this.K=this.pg=this.Ca=null;this.J=0;this.Ea=new g.pq(function(){},c.Z.Ji?4E3:3E3);
g.E(this,this.Ea);this.qb=new g.pq(function(){});
g.E(this,this.qb);this.Aa=new peb(c,function(e,f,h,l,m,n){b5(d,e,f,h,l,m,n)});
this.ea=new g.W({G:"div",S:"iv-drawer",Y:{id:"iv-drawer"},X:[{G:"div",S:"iv-drawer-header",Y:{"aria-role":"heading"},X:[{G:"span",S:"iv-drawer-header-text"},{G:"button",La:["iv-drawer-close-button","ytp-button"],Y:{"aria-label":"Hide cards",tabindex:"0"}}]},{G:"div",S:"iv-drawer-content"}]});g.E(this,this.ea);this.C=this.ea.element;this.kb=new g.GR(this.ea,330);g.E(this,this.kb);this.Jb=g.We("iv-drawer-header-text",this.C);this.u=g.We("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Rb&&d5(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Rb=d.B)&&e5(d)});
this.Oa=new g.iK(this);g.E(this,this.Oa);this.I.addEventListener("videodatachange",this.Ps.bind(this))},yeb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){d5(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){e5(a)});
var c=b.headerText;g.qf(a.Jb,c);a.V&&a.V.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ca=g.BG(b.trackingParams);a.K=g.BG(b.closeTrackingParams);a.pg=g.BG(b.iconTrackingParams)},zeb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.J,d=a.I.W().experiments.rb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"simple",teaserText:g.gG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,Wi:{},Io:null,ll:e.trackingParams?g.BG(e.trackingParams):null,pg:f&&f.trackingParams?g.BG(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
gB:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};f5(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"simple",teaserText:g.gG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:g5(a,c,b,f),sponsored:!1,Wi:c5(f,e,f.command),Io:f.trackingParams?g.BG(f.trackingParams):null,ll:e.trackingParams?g.BG(e.trackingParams):null,pg:l&&l.trackingParams?g.BG(l.trackingParams):null,imageUrl:h5(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.gG(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,gB:null,title:f.title?g.gG(f.title):"",customMessage:f.callToAction?g.gG(f.callToAction):"",url:g.Q(f.command,g.AO).url?X4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.Q(f.command,g.AO).url}):null,onClickCommand:null};f5(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"collaborator",teaserText:g.gG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:g5(a,c,b,e),sponsored:!1,Wi:c5(e,f,e.endpoint),Io:e.trackingParams?g.BG(e.trackingParams):null,ll:f.trackingParams?g.BG(f.trackingParams):null,pg:l&&l.trackingParams?g.BG(l.trackingParams):null,channelId:g.Q(e.endpoint,g.y3).browseId,customMessage:e.customText?g.gG(e.customText):null,zX:h5(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.gG(e.channelName):"",metaInfo:[e.subscriberCountText?g.gG(e.subscriberCountText):""],url:X4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.Q(e.endpoint,g.y3).canonicalBaseUrl?g.Q(e.endpoint,g.y3).canonicalBaseUrl:"/channel/"+g.Q(e.endpoint,g.y3).browseId}),onClickCommand:null};f5(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"playlist",teaserText:g.gG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:g5(a,c,b,e),sponsored:!1,Wi:c5(e,f,e.action),Io:e.trackingParams?g.BG(e.trackingParams):null,ll:f.trackingParams?g.BG(f.trackingParams):null,pg:l&&l.trackingParams?g.BG(l.trackingParams):null,oE:h5(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.gG(e.customMessage):null,playlistVideoCount:g.gG(e.playlistVideoCount),title:e.playlistTitle?g.gG(e.playlistTitle):"",metaInfo:[e.channelName?g.gG(e.channelName):
"",e.videoCountText?g.gG(e.videoCountText):""],url:X4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:web(e.action)}),onClickCommand:null};f5(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"video",teaserText:g.gG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:g5(a,c,b,e),sponsored:!1,Wi:c5(e,f,e.action),Io:e.trackingParams?g.BG(e.trackingParams):null,ll:f.trackingParams?g.BG(f.trackingParams):null,pg:l&&l.trackingParams?g.BG(l.trackingParams):null,oE:h5(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.gG(e.lengthString):null,customMessage:e.customMessage?g.gG(e.customMessage):null,title:e.videoTitle?g.gG(e.videoTitle):"",metaInfo:[e.channelName?g.gG(e.channelName):
"",e.viewCountText?g.gG(e.viewCountText):""],isLiveNow:!!e.badge,url:X4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:web(e.action)}),onClickCommand:null};f5(a,b)}}}}}a.J++},h5=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},g5=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},Beb=function(a,b){if(b=Aeb(a,b))b===a.j&&(a.j=null),a.I.removeCueRange(b.jg.id),g.nf(b.bL),g.Ib(a.cards,b),a.iF(),i5(a)},d5=function(a,b,c){if(!a.B){a.kb.show();
a.Va=new g.pq(function(){g.xq(a.context.I.getRootNode(),g.CX.IV_DRAWER_OPEN)},0);
a.Va.start();a.Oa.T(a.u,"mousewheel",function(h){a.Ea.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.EG();d&&a.Ca&&a.K&&g.wQ(d,[a.Ca,a.K]);b={TRIGGER_TYPE:b};for(var e=g.u(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.XV||(f.XV=!0,Ceb(a.context.logger,f.jg.Wi.kV,b)),d&&g.wQ(d,[f.jg.Io]);G4(a.I);c&&(a.D=new g.pq(function(){a.Ja=a.V;a.Pb.focus()},330),a.D.start())}},e5=function(a){a.B&&(a.kb.hide(),g.JA(a.Oa),g.zq(a.context.I.getRootNode(),g.CX.IV_DRAWER_OPEN),a.B=!1,G4(a.I),a.D&&a.D.stop(),a.D=new g.pq(function(){a.Ja&&(a.Ja.focus(),a.Ja=null)},330),a.D.start())},Eeb=function(a){g.yq(a.xb(),
[g.CX.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.eT(a.I,a.C,5);Deb(a);a.V=g.We("ytp-cards-button",a.I.getRootNode());a.Pb=g.We("iv-drawer-close-button",a.C);a.isInitialized=!0},Deb=function(a){var b=g.We("iv-drawer-close-button",a.C);
a.context.j.Ta(b,"click",a.R2,a);a.context.j.Ta(a.u,"touchend",function(){a.Ea.start()});
a.context.j.Ta(a.u,"scroll",a.m3,a);a.context.u.subscribe("onHideControls",function(){a.Na=!0});
a.context.u.subscribe("onShowControls",function(){a.Na=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Na=g.wq(a.I.getRootNode(),"ytp-autohide")});
a.ma.push(g.jD("iv-button-shown",a.a5,a));a.ma.push(g.jD("iv-button-hidden",a.Z4,a));a.ma.push(g.jD("iv-teaser-shown",a.s_,a));a.ma.push(g.jD("iv-teaser-hidden",a.b5,a));a.ma.push(g.jD("iv-teaser-clicked",a.r_,a))},Feb=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.Q(b.onClickCommand,g.sab))?void 0:c.targetId)?(a.qa=b,!0):!1},Geb=function(a,b){a.qa=b;
var c=a.I.getVideoData();if(!c)return!1;c=a.I.N("embeds_web_enable_video_data_refactoring_offline_and_progress_bar")?g.XN(c):c.multiMarkersPlayerBarRenderer;if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.Q(h[0],g.fPa))?void 0:d.timeRangeStartMillis)||0,a.qa=null,!0}return!1},
f5=function(a,b){if(!Feb(a,b)||Geb(a,b)){var c=Heb(a,b);
if(c){var d={jg:b,bL:c.element,XV:!1};if(!b.onClickCommand){a.isInitialized||Eeb(a);Beb(a,b.id);var e=Ieb(a,d);g.Pb(a.cards,e,0,d);c.Ha(a.u,e);a.iF()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,i5(a),Jeb(a,d),d5(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.I.getCurrentTime(),5E3>c&&c>b.startMs&&Keb(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){Keb(a,d)}),i5(a))}}},Heb=function(a,b){switch(b.type){case "simple":a=a.Aa;
var c=b.displayDomain?{G:"div",S:"iv-card-image-text",xa:b.displayDomain}:void 0;var d=seb(b);c={G:"div",La:["iv-card"],X:[{G:"a",S:"iv-click-target",Y:{href:b.url?W4(b.url)||"":""},X:[Z4(b.imageUrl,c),{G:"div",S:"iv-card-content",X:[Y4("h2",void 0,b.title),d]}]}]};c=new g.W(c);$4(a,g.Re("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Aa;c={G:"div",La:["iv-card","iv-card-channel"],X:[{G:"a",La:["iv-click-target"],Y:{href:W4(b.url)||"","data-ytid":b.channelId},X:[Z4(b.zX),{G:"div",
S:"iv-card-content",X:[qeb(b),{G:"h2",S:"iv-card-primary-link",xa:b.title},reb(b)]}]}]};c=new g.W(c);$4(a,g.Re("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Aa;c={G:"div",La:["iv-card","iv-card-playlist"],X:[{G:"a",S:"iv-click-target",Y:{href:W4(b.url)||""},X:[Z4(b.oE,{G:"div",S:"iv-card-image-overlay",X:[{G:"span",S:"iv-card-playlist-video-count",xa:b.playlistVideoCount}]}),{G:"div",S:"iv-card-content",X:[qeb(b),Y4("h2","iv-card-primary-link",b.title),reb(b)]}]}]};c=new g.W(c);
$4(a,g.Re("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Aa;var e=0!=b.offers.length;c=["iv-card"];d="";var f=seb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({G:"div",S:"iv-card-offer-price",xa:f.price}),f.merchant&&e.push({G:"div",S:"iv-card-offer-merchant",xa:f.merchant}),f={G:"div",X:e});e=b.url?W4(b.url)||"":"";c={G:"div",La:c,Y:{tabindex:"0"},X:[{G:"a",La:["iv-card-image","iv-click-target"],Y:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{G:"div",S:"iv-card-content",X:[b.sponsored?{G:"div",S:"iv-card-sponsored",X:["Sponsored",{G:"div",S:"iv-ad-info-container",X:[{G:"div",S:"iv-ad-info",xa:"{{adInfo}}"},{G:"div",S:"iv-ad-info-icon-container",X:[{G:"div",S:"iv-ad-info-icon"},{G:"div",S:"iv-ad-info-callout"}]}]}]}:"",{G:"a",S:"iv-click-target",Y:{href:e},X:[Y4("h2",d,b.title),f]}]}]};c=new g.W(c);d=g.bf("span");g.qf(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.le(d,"adInfo");$4(a,g.Re("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Aa;d=b.videoDuration?{G:"span",S:"iv-card-video-duration",xa:b.videoDuration}:void 0;f=b.isLiveNow?{G:"span",La:["yt-badge","yt-badge-live"],xa:"LIVE NOW"}:null;e={G:"div",La:["iv-card","iv-card-video"],X:[{G:"a",S:"iv-click-target",Y:{href:(null==(c=b.url)?void 0:W4(c))||""},X:[Z4(b.oE,d),{G:"div",S:"iv-card-content",X:[qeb(b),Y4("h2","iv-card-primary-link",b.title),reb(b),f]}]}]};c=new g.W(e);$4(a,g.Re("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},Ieb=function(a,b){if(0===a.cards.length)return 0;
a=g.Fb(a.cards,function(c){return b.jg.startMs>c.jg.startMs||b.jg.startMs===c.jg.startMs&&b.jg.timestamp>=c.jg.timestamp?!0:!1});
return-1===a?0:a+1},Leb=function(a){if(a.j)return"productListing"===a.j.jg.type;
if(a.I.N("enable_wn_infocards")){var b;return!(null==(b=a.cards)||!b.length)&&g.Jm(a.cards,function(c){return"productListing"===c.jg.type})}return g.Jm(a.cards,function(c){return"productListing"===c.jg.type})},i5=function(a){g.Bq(a.I.getRootNode(),"ytp-cards-shopping-active",Leb(a))},Keb=function(a,b){if(!g.wq(a.I.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.EG(),d=a.j?a.j.jg.pg:a.pg;
c&&d&&g.xQ(c,[d]);a.j=b;i5(a)}(c=a.isInitialized&&"none"==a.xb().style.display)||(c=a.context.I.getPlayerState(),d=0===c&&0===a.context.I.getCurrentTime(),c=!(1===c||3===c||d));c||b.jg.teaserDurationMs&&a.I.Rz(!0,{teaserText:b.jg.teaserText,durationMs:b.jg.teaserDurationMs,onClickCommand:b.jg.onClickCommand});a.qb.isActive()||((!a.B||!a.Ea.isActive()&&a.Na)&&Jeb(a,b),a.qb.start(910+b.jg.teaserDurationMs))}},Jeb=function(a,b){a.ea.Cb?(b=new L4([0,
a.u.scrollTop],[0,b.bL.offsetTop],600,Qdb),a.context.B.Ta(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Ta(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.hR(a.ea,!0),a.u.scrollTop=b.bL.offsetTop,g.hR(a.ea,!1))},j5=function(a){return a.j&&a.j.jg?a.j.jg:a.cards[0]&&a.cards[0].jg?a.cards[0].jg:null},Aeb=function(a,b){return g.Eb(a.cards,function(c){return c.jg.id===b})},k5=function(a,b,c){a5.call(this,a,b);
this.annotation=c;this.isActive=!1},Meb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},l5=function(a,b,c){k5.call(this,a,b,c);
this.u=null;this.K=!1;this.B=null;this.C=!1;this.j=this.J=this.D=null},Neb=function(a,b){var c=void 0===c?0:c;
var d=Idb(b).width;g.yn(b,d);c=new Odb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,Pdb);g.E(a,c);a.context.B.Ta(c,"begin",function(){g.Vn(b,!0)});
c.play()},Qeb=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
La:["iv-branding-context-name"],xa:b.channel_name}),d=a.createElement({G:"div",La:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.OU(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.I),a.j.Ha(d));var f=a.createElement({G:"div",La:["iv-branding-context-subscribe-caret"]}),h=a.createElement({G:"div",La:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.Vn(h,!1);var l=a.createElement({G:"div",La:["branding-context-container-outer"]});l.appendChild(h);g.sn(l,"right",b.image_width+"px");g.df(a.xb(),l);a.B=new g.pq(function(){Oeb(a,h,l)},500);
g.E(a,a.B);a.context.j.Ta(a.xb(),"mouseover",function(){Peb(a,h,l,f,b.image_height)});
a.context.j.Ta(a.xb(),"mouseout",function(){a.B.start()})}},Peb=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.Un(b);a.j||(b.style.width=g.xn(f.width,!0),c.style.width=g.xn(f.width,!0));g.sn(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.sn(d,"right","1px");a.C=!0;g.Vn(b,!0);a.D=new g.pq(function(){g.xq(this.xb(),"iv-branding-active")},0,a);
a.D.start()}},Oeb=function(a,b,c){g.zq(a.xb(),"iv-branding-active");
a.J=new g.pq(function(){g.Vn(b,!1);a.j||(c.style.width=g.xn(0,!0))},250);
a.J.start();a.C=!1},Reb=function(a,b,c,d,e,f,h){this.j=a;
this.B=b;this.Z=c;this.videoData=d;this.logger=e;this.I=f;this.u=h},Seb=function(a,b,c){k5.call(this,a,b,c);
var d=this;this.V=this.isCollapsed=this.ea=!1;this.J=5E3;this.u=this.B=this.j=this.C=null;this.K=this.createElement({G:"div",La:["iv-promo-contents"]});this.D=new g.pq(function(){d.j.setAttribute("aria-hidden","true");g.Vn(d.B,!1);g.Vn(d.u,!0)},700,this);
g.E(this,this.D)},Ueb=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.J=b.collapsedelay_ms||a.J;var d=["iv-promo","iv-promo-inactive"];a.xb().setAttribute("aria-hidden","true");a.xb().setAttribute("aria-label","Promotion");a.xb().tabIndex=0;var e=a.annotation.nf(),f=b.image_url;if(f){var h=a.createElement({G:"div",La:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",Y:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?
(f=a.createElement({G:"span",S:"iv-promo-video-duration",xa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",S:"iv-promo-playlist-length",xa:b.playlist_length.toString()}),h.appendChild(f));e&&b5(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",S:"iv-promo-txt"}),g.qe(f,W4(e)),a.j=f):a.j=a.createElement({G:"div",S:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",X:[{G:"strong",xa:b.text_line_1}]});
var m=a.createElement({G:"p",X:[{G:"span",S:"iv-promo-link",xa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",La:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",La:["iv-button","iv-promo-button"],X:[{G:"span",S:"iv-button-content",xa:f}]});var p=a.createElement({G:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&b5(a,a.xb(),e,a.annotation.id,b.session_data,void 0,c)}g.xq(a.j,"iv-click-target");
e&&b5(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",X:[{G:"span",xa:b.text_line_1}]}),m=a.createElement({G:"p",X:[{G:"strong",xa:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",La:["yt-badge","iv-promo-badge-live"],xa:"LIVE NOW"})),g.xq(a.j,"iv-click-target"),e&&b5(a,a.j,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.K.appendChild(a.j);p&&a.K.appendChild(p);
c=a.createElement({G:"div",S:"iv-promo-actions"});a.u=a.createElement({G:"button",La:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.j.Ta(a.u,"click",function(q){Teb(a,5E3,q)});
c.appendChild(a.u);g.Vn(a.u,!1);a.context.j.Ta(a.xb(),"mouseover",a.h4,a);a.context.j.Ta(a.xb(),"mouseout",a.g4,a);a.context.j.Ta(a.xb(),"touchend",function(q){Teb(a,5E3,q)});
a.B=a.createElement({G:"button",La:["iv-promo-close","ytp-button"]});a.B.title="Close";a.context.j.Ta(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.b4:a.a4,a);c.appendChild(a.B);g.yq(a.xb(),d);h&&(g.df(a.xb(),h),n&&h.appendChild(n));g.df(a.xb(),a.K);g.df(a.xb(),c)},Teb=function(a,b,c){c.stopPropagation();
Veb(a);Web(a,b);a.j.focus()},Xeb=function(a){a.isCollapsed||a.V||a.C||(g.xq(a.xb(),"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},Veb=function(a){a.D.stop();
a.isCollapsed&&(g.Aq(a.xb(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Vn(a.u,!1),g.Vn(a.B,!0))},Web=function(a,b){a.C||(a.C=g.Xf(function(){Yeb(this);
Xeb(this)},b,a))},Yeb=function(a){a.C&&(g.La.clearTimeout(a.C),a.C=null)},Zeb=function(a){this.I=a},Ceb=function(a,b,c){b&&(c?m5(a,b.map(function(d){return g.eq(d,c)})):m5(a,b))},m5=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.u(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.TC(m,f);d&&(e++,0!==d&&a.I.sendVideoStatsEngageEvent(d,f))},$eb=function(a){g.fU.call(this,a);
var b=this;this.ea=this.K=!1;this.loadNumber=0;this.J={};this.logger=new Zeb(this.player);this.C=new g.iK(this);this.D=this.Jw=null;this.events=new g.iK(this);this.lh=this.V=this.j=null;this.ma=[];g.E(this,this.C);this.C.T(this.player,"onVideoAreaChange",function(){b.oa("onVideoAreaChange")});
this.C.T(this.player,"onHideControls",function(){b.oa("onHideControls")});
this.C.T(this.player,"onShowControls",function(){b.oa("onShowControls")});
this.C.T(this.player,"resize",function(d){b.oa("resize",d)});
this.C.T(this.player,"presentingplayerstatechange",function(d){b.oa("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.t_,this);this.subscribe("resize",this.uH,this);this.player.W().Ja.subscribe("vast_info_card_add",this.iX,this);g.E(this,this.events);this.qa=this.createElement({G:"div",S:"video-custom-annotations"});this.u=new g.W({G:"div",La:["ytp-player-content","ytp-iv-player-content"]});g.E(this,this.u);g.eT(this.player,this.u.element,4);this.u.hide();this.B=new g.W({G:"div",La:["ytp-iv-video-content"]});g.E(this,this.B);a=this.createElement({G:"div",S:"video-annotations"});
a.appendChild(this.qa);this.B.element.appendChild(a);this.zw()&&this.load();var c=this.createElement({G:"style"});(g.Pe("HEAD")[0]||document.body).appendChild(c);g.sb(this,function(){g.nf(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},afb=function(a){a=a.createElement({G:"div",
La:["annotation","annotation-type-custom"]});g.Vn(a,!1);return a},bfb=function(a,b){b=!b.isCued()&&!g.JP(b,1024);
g.hR(a.u,b);g.hR(a.B,b)},cfb=function(a,b,c){a.K=!0;
a.D=g.Dz(b,c)},dfb=function(a,b){for(var c={},d=g.u(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ua(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(dfb(a,e))}return c},hfb=function(a){var b=a.player.getVideoData();
if(b.Oa){var c=a.player.W().Ja.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.wz(h)&&h.responseXML?h.responseXML:null)&&efb(a,h)}};
g.hB()&&(d.onFinish=ffb(a,d.onFinish));d.postParams={ic_only:"1"};gfb(d,c);a.K=!0;g.Dz(b.Oa,d)}}},gfb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.iB&&(a.postParams.ic_coll=b.iB);b.cL&&(a.postParams.ic_xml=b.cL);b.II&&(a.postParams.ic_track=b.II)},ifb=function(a){var b=new g.W({G:"div"});
g.Vn(b.element,!1);var c=new xeb(a.player,b.element,n5(a));g.E(c,b);b.Ha(a.u.element);c.dE();return c},n5=function(a){if(!a.V){var b=new Rdb(a);
g.E(a,b);var c=new g.Hl(a);g.E(a,c);a.V=new Reb(b,c,a.player.W(),a.player.getVideoData(),a.logger,a.player,a.Fi)}return a.V},efb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.EG();if(e){var f=g.DG();f&&g.iz(g.XAa)(void 0,e,f,[g.BG(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=dfb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=V4(f.type,jfb),p=V4(f.style,kfb),q=geb(f.data),t=0!==q.length?JSON.parse(q):{};var v=f.action;f=meb;if(null==v)var y=null;else if(g.Sa(v)){l=[];for(var A=g.u(v),G=A.next();!G.done;G=A.next()){var N=f(G.value);
N&&l.push(N)}y=l}else{var L=f(v);y=L?[L]:[]}e=m&&n?new neb(m,n,p,y,t):null}else e=null}catch(na){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var H=afb(f),U=null;switch(l.type){case "branding":if(f.player.W().Zd)break;f.u.element.appendChild(H);U=new l5(H,n5(f),l);break;case "promotion":g.eT(f.player,H,4),U=new Seb(H,n5(f),l)}U&&U.dE();if(f=U)g.E(a,f),a.J[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=ifb(a),g.E(a,a.j));if("card"===e.type){c=a.j;var Z=e&&e.data&&e.data.card_type;
f=e.data;if(Z)switch(l=f.tracking||{},l={kV:l.impression,click:l.click,close:l.close,IY:l.teaser_impression,FI:l.teaser_click},H=f.tracking_params||{},U=null,Z){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Wi:l,Io:H.card?g.BG(H.card):null,ll:H.teaser?g.BG(H.teaser):null,pg:H.icon?g.BG(H.icon):null,channelId:f.channel_id,
customMessage:f.custom_message?f.custom_message:null,zX:f.image_url,title:f.title,metaInfo:f.meta_info,url:X4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};f5(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Wi:l,Io:H.card?g.BG(H.card):null,ll:H.teaser?
g.BG(H.teaser):null,pg:H.icon?g.BG(H.icon):null,oE:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:X4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};f5(c,e);break;case "productListing":f.signin_url&&(U=X4({target:"current",value:f.signin_url}));Z=[];for(var fa=f.offers||[],ta=0;ta<fa.length;ta++)Z.push(new teb(g.Ie(fa[ta].merchant),g.Ie(fa[ta].price)));
e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Wi:l,Io:H.card?g.BG(H.card):null,ll:H.teaser?g.BG(H.teaser):null,pg:H.icon?g.BG(H.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,gB:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:X4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),wab:U,vab:f.signin_title?f.signin_title:void 0,uab:f.signin_message?f.signin_message:void 0,offers:Z,onClickCommand:null};f5(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Wi:l,Io:H.card?g.BG(H.card):
null,ll:H.teaser?g.BG(H.teaser):null,pg:H.icon?g.BG(H.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,gB:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:X4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};f5(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Wi:l,Io:H.card?g.BG(H.card):null,ll:H.teaser?g.BG(H.teaser):null,pg:H.icon?g.BG(H.icon):null,oE:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:X4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},f5(c,e)}}else yeb(a.j,e);c=!0}}c&&
(G4(a.player),a.uH())},lfb=function(a,b){var c=!1;
a.j||(a.j=ifb(a),g.E(a,a.j));for(var d=g.u(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(zeb(a.j,e.cardRenderer),c=!0);if(c){var f;null!=(f=a.player.getVideoData())&&g.TO(f)||(c=a.j,d=b.headerText?g.gG(b.headerText):"",g.qf(c.Jb,d),c.V&&c.V.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ca=b.trackingParams?g.BG(b.trackingParams):null,c.K=b.closeButton.infoCardIconRenderer.trackingParams?g.BG(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.pg=b.icon.infoCardIconRenderer.trackingParams?g.BG(b.icon.infoCardIconRenderer.trackingParams):null,a.uH());G4(a.player)}},mfb=function(a,b,c,d,e){if(!a.player.W().Zd){var f=[];
b.navigationEndpoint&&g.Q(b.navigationEndpoint,g.y3)&&g.Q(b.navigationEndpoint,g.y3).browseId&&f.push(new jeb("openUrl","click",new heb("/channel/"+g.Q(b.navigationEndpoint,g.y3).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.Q(b.subscribeButton,
g.MO)){d.channel_id=g.Q(b.subscribeButton,g.MO).channelId;var l;b=g.Q(b.subscribeButton,g.MO);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.gG(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.gG(b.subscriberCountText))):(b.subscriberCountText&&(e=g.gG(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.gG(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.Q(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.z3))?void 0:m.url)||"";l={subscribeText:g.gG(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.gG(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new neb(c,"branding","branding",f,d);l=afb(a);a.u.element.appendChild(l);f=new l5(l,n5(a),f);f.dE();g.E(f,f);a.J[c]=f}},ffb=function(a,b){return function(){var c=g.Fa.apply(0,arguments);
a.isDisposed()||a.ma.push(g.hq.Ei(function(){b.apply(null,g.oa(c))}))}},nfb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.XS.prototype.Rz=g.ca(18,function(a,b){var c=g.tU(this.Bb());c&&c.Rz(a,b)});
var I4={},J4=null;g.db(L4,g.Jq);g.k=L4.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.md())return!1;K4(this);this.startTime=a=g.Za();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.C=this.startTime;this.progress||this.kH();this.Ml("play");-1==this.j&&this.Ml("resume");this.j=1;var b=g.Wa(this);b in I4||(I4[b]=this);Kdb();Ldb(this,a);return!0};
g.k.stop=function(a){K4(this);this.j=0;a&&(this.progress=1);Mdb(this,this.progress);this.Ml("stop");this.Nq()};
g.k.pause=function(){this.md()&&(K4(this),this.j=-1,this.Ml("pause"))};
g.k.va=function(){0==this.j||this.stop(!1);this.Ml("destroy");L4.Lf.va.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.uJ=function(){this.Ml("animate")};
g.k.Ml=function(a){this.dispatchEvent(new Ndb(a,this))};
g.db(Ndb,g.wb);g.db(M4,L4);M4.prototype.B=function(){};
M4.prototype.uJ=function(){this.B();M4.Lf.uJ.call(this)};
M4.prototype.Nq=function(){this.B();M4.Lf.Nq.call(this)};
M4.prototype.kH=function(){this.B();M4.Lf.kH.call(this)};
g.db(Odb,M4);Odb.prototype.B=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.x(Rdb,g.C);g.k=Rdb.prototype;g.k.Ta=function(a,b,c,d){c=(0,g.Xa)(c,d||this.u);a=g.BA(a,b,c);this.j.push(a);return a};
g.k.NG=function(a,b,c,d){c=(0,g.Xa)(c,d||this.u);a=g.vna(a,b,c);this.j.push(a);return a};
g.k.Hc=function(a){g.CA(a);g.Ib(this.j,a)};
g.k.Kf=function(){g.CA(this.j);this.j.length=0};
g.k.va=function(){this.Kf();g.C.prototype.va.call(this)};g.x(Udb,g.fU);g.k=Udb.prototype;g.k.load=function(){g.fU.prototype.load.call(this);if(!P4(this)){var a=g.Pya(this.player.getVideoData());a?(a=Tdb(a,Vdb(this)),Q4(this,a,!1)):Wdb(this)}};
g.k.unload=function(){Q4(this,null);this.B&&(this.B.abort(),this.B=null);g.fU.prototype.unload.call(this)};
g.k.Bh=function(a,b){return P4(this)?"loadCustomEndscreenRenderer"===a?(a=Tdb(b,"new"),Q4(this,a),!0):null:null};
g.k.getOptions=function(){return P4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Hb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<ofb.length;f++){var h=Math.abs(b.width-ofb[f]);if(-1===e||d>=h)e=f,d=h}d=pfb[e];this.u&&g.sn(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Cn(e.element,m,f);g.yn(e.element,n,p);g.Aq(e.element,qfb);256<m||256<f?g.xq(e.element,"ytp-ce-large-round"):96<m||96<f?g.xq(e.element,"ytp-ce-medium-round"):g.xq(e.element,"ytp-ce-small-round");g.Aq(e.element,rfb);m=h.left+h.width/2;h=h.top+l/2;g.xq(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Aq(e.element,pfb);g.xq(e.element,d);(e=g.Qe(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.sn(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())U4(this,this.endscreen.impressionUrls),(a=g.EG())&&this.endscreen.visualElement&&g.vQ(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.D[a];g.xq(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.xq(b,"ytp-ce-shown");U4(this,c.impressionUrls);(b=g.EG())&&g.vQ(b,c.visualElement);this.player.W().J&&this.player.Qa("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.zq(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.zq(b,"ytp-ce-shown");this.player.W().J&&this.player.Qa("endscreenelementhidden",a)}};
g.k.n8=function(a){var b=this;a.target===window&&(new g.pq(function(){for(var c=g.u(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.Aq(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var ofb=[346,426,470,506,570,640,853,1280,1920],pfb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),rfb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],qfb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var ieb={Sna:"current",DMa:"new"};var keb={CLOSE:"close",dQa:"openUrl",SUBSCRIBE:"subscribe"},leb={xma:"click",CLOSE:"close",vya:"hidden",SUa:"rollOut",TUa:"rollOver",pWa:"shown"};neb.prototype.nf=function(){var a=oeb(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var kfb={Hha:"anchored",MZ:"branding",CHANNEL:"channel",Ina:"cta",yya:"highlightText",xCa:"label",PLAYLIST:"playlist",xSa:"popup",UYa:"speech",SUBSCRIBE:"subscribe",U0a:"title",VIDEO:"video",R6a:"website"},jfb={MZ:"branding",tka:"card",Ppa:"drawer",xya:"highlight",uIa:"marker",NTa:"promotion",TEXT:"text",p8a:"widget"};g.x(a5,g.C);g.k=a5.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.ZF(a,b,{id:c,namespace:"annotations_module"});d&&this.bb.set(a,d);e&&this.jb.set(a,e);this.context.I.cf([a])};
g.k.dE=function(){this.context.u.subscribe("resize",this.iF,this)};
g.k.xb=function(){return this.element};
g.k.vJ=function(a,b,c,d,e,f){if(this.ub)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.nf(this.xb())};
g.k.iF=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=W4(a);if(f){var h=veb(f,a.target),l=function(){a.j&&e.context.I.pauseVideo();var m=e.context.videoData.Cd||!1,n=g.oz(f||"");m&&n&&(n.v||n.list)?e.context.I.Wn(n.v,b,n.list,!1):g.DP(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);m5(this.context.logger,c,l,d);ueb(f)||(c=g.EG(),d=b.itct,c&&d&&g.yQ(c,g.BG(d)))}};
g.k.va=function(){this.bb.clear();this.jb.clear();g.C.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.E(this,a);return a.element};g.x(xeb,a5);g.k=xeb.prototype;g.k.Ps=function(){this.qa&&f5(this,this.qa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.I.getRootNode())?(a=g.Un(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.iF=function(){var a=this.isAvailable();g.Vn(this.xb(),a);g.Bq(this.context.I.getRootNode(),g.CX.IV_DRAWER_ENABLED,a);G4(this.I)};
g.k.destroy=function(){this.I.Rz(!1);try{this.I.getRootNode().removeChild(this.C)}catch(a){}g.kD(this.ma);g.JA(this.Oa);this.Va&&this.Va.dispose();this.D&&this.D.dispose();a5.prototype.destroy.call(this)};
g.k.R2=function(){if(this.B){m5(this.context.logger,j5(this).Wi.close);var a=g.EG();a&&this.K&&g.yQ(a,this.K);e5(this)}};
g.k.m3=function(){g.Bq(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.a5=function(){var a=g.EG(),b=j5(this);b=b?b.pg:this.pg;a&&b&&g.wQ(a,[b])};
g.k.Z4=function(){var a=g.EG(),b=j5(this);b=b?b.pg:this.pg;a&&b&&g.xQ(a,[b])};
g.k.s_=function(){var a=j5(this);m5(this.context.logger,a.Wi.IY);var b=g.EG();b&&a&&g.wQ(b,[a.ll,a.pg])};
g.k.b5=function(){var a=g.EG(),b=j5(this);a&&b&&g.xQ(a,[b.ll])};
g.k.r_=function(a){var b=j5(this),c=g.EG();this.j?a?(a=this.context.logger,m5(a,b.Wi.FI),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.ll&&g.yQ(c,b.ll)):(a=this.context.logger,m5(a,b.Wi.FI),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.pg&&g.yQ(c,b.pg)):(a=this.context.logger,m5(a,b.Wi.FI),a.I.sendVideoStatsEngageEvent(4,void 0),c&&this.pg&&g.yQ(c,this.pg))};g.x(k5,a5);k5.prototype.dE=function(){a5.prototype.dE.call(this);Meb(this)};
k5.prototype.show=function(){a5.prototype.show.call(this);var a=g.EG(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.wQ(a,[g.BG(b.itct)])};
k5.prototype.hide=function(){a5.prototype.hide.call(this);var a=g.EG(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.xQ(a,[g.BG(b.itct)])};g.x(l5,k5);
l5.prototype.show=function(){if(!this.isActive){k5.prototype.show.call(this);if(!this.K){g.xq(this.xb(),"iv-branding");var a=this.annotation.data;this.u=this.createElement({G:"img",La:["branding-img","iv-click-target"],Y:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Vn(this.u,!1);var b=this.createElement({G:"button",La:["branding-img-container","ytp-button"]});b.appendChild(this.u);this.xb().appendChild(b);var c=this.annotation.nf();c&&b5(this,b,
c,this.annotation.id,a.session_data);Qeb(this,a);this.K=!0}g.Vn(this.xb(),!0);this.isActive=!0;this.u&&(Neb(this,this.u),g.xq(this.context.I.getRootNode(),"ytp-branding-shown"))}};
l5.prototype.hide=function(){this.isActive&&(k5.prototype.hide.call(this),g.Vn(this.xb(),!1),this.isActive=!1,g.zq(this.context.I.getRootNode(),"ytp-branding-shown"))};
l5.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);k5.prototype.destroy.call(this)};g.x(Seb,k5);g.k=Seb.prototype;g.k.show=function(){this.isActive||(k5.prototype.show.call(this),this.ea||(Ueb(this),this.ea=!0),g.Vn(this.xb(),!0),g.Xf(function(){g.zq(this.xb(),"iv-promo-inactive")},100,this),this.xb().removeAttribute("aria-hidden"),this.isActive=!0,Yeb(this),Veb(this),Web(this,this.J))};
g.k.hide=function(){this.isActive&&(g.xq(this.xb(),"iv-promo-inactive"),this.isActive=!1,this.xb().setAttribute("aria-hidden","true"))};
g.k.vJ=function(a,b,c,d,e,f){return this.isCollapsed?!1:k5.prototype.vJ.call(this,a,b,c,d,e,f)};
g.k.h4=function(a){this.V=!0;Teb(this,500,a)};
g.k.g4=function(){this.V=!1;Xeb(this)};
g.k.a4=function(a){a.stopPropagation();this.hide()};
g.k.b4=function(a){a.stopPropagation();Yeb(this);this.isCollapsed=!0;g.xq(this.xb(),"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();k5.prototype.destroy.call(this)};g.x($eb,g.fU);g.k=$eb.prototype;g.k.Bh=function(a,b){if(!nfb(this.player.W().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.W8a(b))&&efb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(Beb(this.j,b),G4(this.player)),!0}return null};
g.k.getOptions=function(){return nfb(this.player.W().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.zw=function(){var a=this.player.W(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return b.Cd&&a.ma||g.RS(this.player.app)?!1:1===c&&!b.rS||a.Ja.get(b.videoId)||g.UO(b)||g.Qya(b)?!0:!1};
g.k.uH=function(){if(this.B){var a=this.player.ob().getVideoContentRect(!0);g.Cn(this.B.element,a.width,a.height);g.yn(this.B.element,a.left,a.top)}if(this.j){var b=this.player.Ek();a=this.j;b=b.width;g.Bq(a.C,"iv-drawer-small",426>=b);g.Bq(a.C,"iv-drawer-big",1280<=b)}};
g.k.t_=function(a){bfb(this,a.state);g.JP(a.state,2)&&(this.vk()&&this.Ho()&&2!==this.player.getPresentingPlayerType()&&this.Sz(!1),this.Rz(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.D=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.wz(h)&&h.responseXML?h.responseXML:null)&&(efb(b,h),g.xq(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.fU.prototype.load.call(this);bfb(this,this.player.Lb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.hB()&&(a=ffb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.D=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.W().Ja.get(d);f&&gfb(e,f);f=f&&(f.cL||f.iB);if(!c.uA||f)c.Oa?cfb(this,c.Oa,e):(this.Jw=function(){if(!b.K)b.onVideoDataChange(e);var h=b.player.getVideoData();if((null==h?0:g.TO(h))&&!b.ea){var l,m;if(h=null==(l=h.Ad)?void 0:null==(m=l.cards)?void 0:m.cardCollectionRenderer)b.ea=!0,lfb(b,h),h.headerText&&b.lh&&(l=g.gG(h.headerText),b.lh.setAttribute("title",l))}},this.player.addEventListener("videodatachange",
this.Jw));
g.eT(this.player,this.B.element,4);this.uH();(f=g.UO(c))&&lfb(this,f);(f=g.Qya(c))&&f.featuredChannel&&mfb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.lh=g.We("ytp-cards-button",this.player.getRootNode())};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Oa&&cfb(this,b.Oa,a)};
g.k.unload=function(){this.player.Ne("annotations_module");for(var a=g.u(Object.keys(this.J)),b=a.next();!b.done;b=a.next())this.J[b.value].destroy();this.V=null;this.j&&(this.j.destroy(),this.j=null,G4(this.player));this.K=!1;this.D&&(this.D.abort(),this.D=null);this.ea=!1;this.J={};this.u.hide();g.fU.prototype.unload.call(this);this.B.detach();this.Jw&&(this.player.removeEventListener("videodatachange",this.Jw),this.Jw=null)};
g.k.iX=function(a){a===this.player.getVideoData().videoId&&(this.loaded?hfb(this):this.load())};
g.k.vk=function(){var a;return(null==(a=this.j)?void 0:a.isAvailable())||this.ea};
g.k.Ho=function(){return!!this.j&&this.j.B};
g.k.Sz=function(a,b,c){b=void 0===b?!1:b;this.vk();this.j&&(a?c?d5(this.j,c,b):d5(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):e5(this.j))};
g.k.Rz=function(a,b){this.player.oa(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.va=function(){this.player.W().Ja.unsubscribe("vast_info_card_add",this.iX,this);g.zq(this.player.getRootNode(),g.CX.IV_DRAWER_OPEN);for(var a=this.ma,b=g.hq,c=0,d=a.length;c<d;c++)b.Om(a[c]);this.ma.length=0;g.fU.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.E(this,a);return a.element};g.eU("annotations_module",$eb);g.eU("creatorendscreen",Udb);})(_yt_player);
